USE [master]


CREATE DATABASE [@NewDatabaseName]
 CONTAINMENT = NONE
 ON  PRIMARY ( NAME = N'@NewDatabaseName', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\@NewDatabaseName.mdf' , SIZE = 18750KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON ( NAME = N'@NewDatabaseName_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\@NewDatabaseName_log.ldf' , SIZE = 1250KB , MAXSIZE = 2048GB , FILEGROWTH = 10% )
											   

ALTER DATABASE [@NewDatabaseName] SET COMPATIBILITY_LEVEL = 120


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [@NewDatabaseName].[dbo].[sp_fulltext_database] @action = 'enable'
end


ALTER DATABASE [@NewDatabaseName] SET ANSI_NULL_DEFAULT OFF 


ALTER DATABASE [@NewDatabaseName] SET ANSI_NULLS OFF 


ALTER DATABASE [@NewDatabaseName] SET ANSI_PADDING OFF 


ALTER DATABASE [@NewDatabaseName] SET ANSI_WARNINGS OFF 


ALTER DATABASE [@NewDatabaseName] SET ARITHABORT OFF 


ALTER DATABASE [@NewDatabaseName] SET AUTO_CLOSE OFF 


ALTER DATABASE [@NewDatabaseName] SET AUTO_SHRINK OFF 


ALTER DATABASE [@NewDatabaseName] SET AUTO_UPDATE_STATISTICS ON 


ALTER DATABASE [@NewDatabaseName] SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE [@NewDatabaseName] SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE [@NewDatabaseName] SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE [@NewDatabaseName] SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE [@NewDatabaseName] SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE [@NewDatabaseName] SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE [@NewDatabaseName] SET  DISABLE_BROKER 


ALTER DATABASE [@NewDatabaseName] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE [@NewDatabaseName] SET DATE_CORRELATION_OPTIMIZATION OFF 


ALTER DATABASE [@NewDatabaseName] SET TRUSTWORTHY OFF 


ALTER DATABASE [@NewDatabaseName] SET ALLOW_SNAPSHOT_ISOLATION OFF 


ALTER DATABASE [@NewDatabaseName] SET PARAMETERIZATION SIMPLE 


ALTER DATABASE [@NewDatabaseName] SET READ_COMMITTED_SNAPSHOT OFF 


ALTER DATABASE [@NewDatabaseName] SET HONOR_BROKER_PRIORITY OFF 


ALTER DATABASE [@NewDatabaseName] SET RECOVERY FULL 


ALTER DATABASE [@NewDatabaseName] SET  MULTI_USER 


ALTER DATABASE [@NewDatabaseName] SET PAGE_VERIFY CHECKSUM  


ALTER DATABASE [@NewDatabaseName] SET DB_CHAINING OFF 


ALTER DATABASE [@NewDatabaseName] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 


ALTER DATABASE [@NewDatabaseName] SET TARGET_RECOVERY_TIME = 0 SECONDS 


ALTER DATABASE [@NewDatabaseName] SET DELAYED_DURABILITY = DISABLED 


ALTER DATABASE [@NewDatabaseName] SET  READ_WRITE 



