USE [@NewDatabaseName]

INSERT INTO [dbo].[dbConfig] ([Id],[description],[descValue]) VALUES (1,'Start Day','06:00')

INSERT INTO [dbo].[DishesInOrderStatus] ([Id],[Name]) VALUES (1,N'ברישום')
INSERT INTO [dbo].[DishesInOrderStatus] ([Id],[Name]) VALUES (2,N'הודפס')
INSERT INTO [dbo].[DishesInOrderStatus] ([Id],[Name]) VALUES (6,N'ביטול')
										  
INSERT INTO [dbo].[DishCategories] ([Id],[CategotyName],[groupId]) VALUES (0,N'לא מקוטלג',0)
INSERT INTO [dbo].[DishCategories] ([Id],[CategotyName],[groupId]) VALUES (9998,N'תוספות',0)
INSERT INTO [dbo].[DishCategories] ([Id],[CategotyName],[groupId]) VALUES (9999,N'תתי פריטים',0)
								 
INSERT INTO[dbo].[Dishes] ([Id],[Name],[dishCategoryId]) VALUES(0, N'לא מקוטלג',0)

INSERT INTO [dbo].[branchActivityType] ([activityName],[alertLevel]) VALUES (N'הזמנה בוטלה','danger')
INSERT INTO [dbo].[branchActivityType] ([activityName],[alertLevel]) VALUES (N'פריט בוטל','warning')
INSERT INTO [dbo].[branchActivityType] ([activityName],[alertLevel]) VALUES (N'הנחה לפריט','warning')
INSERT INTO [dbo].[branchActivityType] ([activityName],[alertLevel]) VALUES (N'שחזור הזמנה','info')
INSERT INTO [dbo].[branchActivityType] ([activityName],[alertLevel]) VALUES (N'עובד נכנס למשמרת','info')
INSERT INTO [dbo].[branchActivityType] ([activityName],[alertLevel]) VALUES (N'עובד יוצא ממשמרת','info')

INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (1,N'אשראי')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (2,N'מזומן')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (3,N'שיק')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (4,N'שובר')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (5,N'הקפה')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (6,N'טיפים מלצרים')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (7,N'ValueCard')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (8,N'תשלום חדש 1')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (9,N'תשלום חדש 2')

INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (10,N'Sodexo')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (11,N'MultiPass')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (12,N'תן ביס')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (13,N'הנחה')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (14,N'פיצוי תשלום ללקוח')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (15,N'DelivApp')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (16,N'הנחה')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (17,N'פחת')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (18,N'----לא בשימוש----')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (19,N'----לא בשימוש----')

INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (20,N'התחייבות לתשלום')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (21,N'Iservice')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (22,N'Shelly')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (23,N'Skipper')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (24,N'משלוחה')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (25,N'Cellarix')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (26,N'MicroDeal')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (27,N'Goodi')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (28,N'Rewardy')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (29,N'Optima')

INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (30,N'FoodBook')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (31,N'BitGo')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (32,N'משלוחה')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (33,N'Keeperz')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (34,N'Beengo')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (35,N'תשלום חדש 5')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (36,N'מגה לאן')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (37,N'תשלום חדש 7')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (38,N'תשלום חדש 8')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (39,N'Rest')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (40,N'תו הזהב')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (41,N'MiniHotel')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (42,N'CreditX')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (43,N'PaidIt')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (44,N'SimplyClub')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (45,N'משלוחים - myweb')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (46,N'משלוחים - bazelet')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (47,N'משלוחים - amazing')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (48,N'Fortress')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (49,N'Knupo')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (50,N'Verofone')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (51,N'Zooz - Rest')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (52,N'תמורה')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (53,N'Modularity')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (54,N'BeeClub')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (55,N'גודי חיצוני')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (56,N'תשלום חיצוני 56')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (57,N'BITE')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (58,N'sanjer')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (59,N'עמיהוד קפה נחת')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (60,N'Urbanana')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (61,N'inManage')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (62,N'dotBeer')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (63,N'Venos')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (64,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (65,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (66,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (67,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (68,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (69,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (70,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (71,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (72,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (73,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (74,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (75,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (76,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (77,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (78,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (79,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (80,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (81,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (82,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (83,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (84,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (85,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (86,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (87,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (88,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (89,N'תשלום X')
INSERT INTO [dbo].[paymentTypes] ([Id],[typeName]) VALUES (90,N'תשלום X')

INSERT [dbo].[ShiftsGlobals] ([startHour], [endHour], [Name]) VALUES (CAST(N'07:00:00' AS Time), CAST(N'12:59:59' AS Time), N'בוקר')
INSERT [dbo].[ShiftsGlobals] ([startHour], [endHour], [Name]) VALUES (CAST(N'13:00:00' AS Time), CAST(N'15:59:59' AS Time), N'צהריים')
INSERT [dbo].[ShiftsGlobals] ([startHour], [endHour], [Name]) VALUES (CAST(N'16:00:00' AS Time), CAST(N'19:59:59' AS Time), N'אחרי צהריים')
INSERT [dbo].[ShiftsGlobals] ([startHour], [endHour], [Name]) VALUES (CAST(N'20:00:00' AS Time), CAST(N'23:59:59' AS Time), N'ערב')
INSERT [dbo].[ShiftsGlobals] ([startHour], [endHour], [Name]) VALUES (CAST(N'00:00:00' AS Time), CAST(N'06:59:59' AS Time), N'לילה')



INSERT INTO [dbo].[shifts] ([Name],[value]) VALUES (N'רגילה',100)
INSERT INTO [dbo].[shifts] ([Name],[value]) VALUES (N'שבת',125)
INSERT INTO [dbo].[shifts] ([Name],[value]) VALUES (N'מיוחדת',150)

INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (0,N'מלצרית',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (1,N'מנהל',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (2,N'ברמן',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (3,N'עובד מטבח',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (4,N'שליח',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (5,N'טלפן',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (6,N'קופה',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (7,N'מארחת',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (8,N'שוטף כלים',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (9,N'מאבטח',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (10,N'אחמש',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (11,N'11',0)
INSERT INTO [dbo].[WorkerJobType] ([Id],[JobName],[CanOpenOrder]) VALUES (12,N'12',0)



INSERT INTO [dbo].[Workers] ([Id],[workerJobTypeId],[Name],[InShift],[Active]) VALUES (0,0,N'עובד לא רשום', 'false', 'true')

